//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point8_5
	{
		public static Vector3 stair = new Vector3 (1.62f, 1.0F, 9.33f);
		public static Vector3 evelator = new Vector3 (22.6f, 1.0F, 1.31f);

		
		static Vector3 o1 = new Vector3 (3.230011F, 1.5F, 13.69F);
		static Vector3 o2 = new Vector3 (10.48999F, 1.5F, 9.830002F);
		
		static Vector3[] office1 = new Vector3[] { stair, o1 };
		static Vector3[] office2 = new Vector3[] { stair, o2 };
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point8_5 ()
		{
			
			/*LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);

			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);*/

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
		}
	}
}

