//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point8_5handicap
	{
		public static Vector3 evelator = new Vector3 (1.06f, 1.0F, 17.42f);
		
		
		static Vector3 o1 = new Vector3 (3.230011F, 1.5F, 13.69F);
		static Vector3 o2 = new Vector3 (9.48F, 1.5F, 10.07F);

		
		static Vector3 f2 = new Vector3 (0.93F, 1.5F, 10.07F);

		static Vector3[] office1 = new Vector3[] { evelator, o1 };
		static Vector3[] office2 = new Vector3[] { evelator, f2, o2 };
		
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();


		public Point8_5handicap ()
		{
			
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
		}
	}
}

