//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.IO;
namespace AssemblyCSharp
{
	public class Point8_3handicap
	{
		static Vector3 evelator = new Vector3 (2.350006F, 1.0F, 16.88F);
		
		static Vector3 o1 = new Vector3 (19.54999F, 1.5F, -17.22F);
		static Vector3 o2 = new Vector3 (23.25F, 1.5F, -3.059998F);
		static Vector3 o3 = new Vector3 (23.25F, 1.5F, -1.229996F);
		static Vector3 o4 = new Vector3 (23.25F, 1.5F, 0.9499969F);
		static Vector3 o5 = new Vector3 (23.25F, 1.5F, 3.369995F);
		static Vector3 o6 = new Vector3 (23.25F, 1.5F, 5.850006F);
		static Vector3 o7 = new Vector3 (23.25F, 1.5F, 8.029999F);
		static Vector3 o8 = new Vector3 (23.25F, 1.5F, 10.33F);
		static Vector3 o9 = new Vector3 (23.25F, 1.5F, 12.63F);
		static Vector3 o10 = new Vector3 (23.25F, 1.5F, 14.81F);
		static Vector3 o11 = new Vector3 (23.25F, 1.5F, 16.99001F);
		static Vector3 o12 = new Vector3 (23.25F, 1.5F, 19.23F);
		static Vector3 o13 = new Vector3 (23.25F, 1.5F, 21.3F);
		static Vector3 o14 = new Vector3 (23.25F, 1.5F, 25.31F);
		static Vector3 o15 = new Vector3 (21.12F, 1.5F, 28.67F);
		static Vector3 o16 = new Vector3 (18.29001F, 1.5F, 28.67F);
		static Vector3 o17 = new Vector3 (15.39999F, 1.5F, 28.67F);
		static Vector3 o18 = new Vector3 (10.62F, 1.5F, 28.67F);
		static Vector3 o19 = new Vector3 (5.429993F, 1.5F, 28.67F);
		static Vector3 o20 = new Vector3 (1.769989F, 1.5F, 28.67F);
		static Vector3 o21 = new Vector3 (-1.470001F, 1.5F, 28.67F);
		static Vector3 o22 = new Vector3 (-3.769989F, 1.5F, 28.67F);
		static Vector3 o23 = new Vector3 (-5.600006F, 1.5F, 28.67F);
		static Vector3 o24 = new Vector3 (-7.899994F, 1.5F, 26.77F);
		static Vector3 o25 = new Vector3 (-9.25F, 1.5F, 23.75F);
		static Vector3 o26 = new Vector3 (-9.25F, 1.5F, 19.91F);
		static Vector3 o27 = new Vector3 (-12.23001F, 1.5F, 15.78F);
		static Vector3 o28 = new Vector3 (-15.78F, 1.5F, 6.539993F);
		static Vector3 o29 = new Vector3 (-11.76001F, 1.5F, 8.809998F);
		static Vector3 o30 = new Vector3 (-9.309998F, 1.5F, 8.770004F);
		static Vector3 o31 = new Vector3 (-6.660004F, 1.5F, 9.600006F);
		static Vector3 o32 = new Vector3 (-6.660004F, 1.5F, 6.899994F);
		static Vector3 o33 = new Vector3 (-6.660004F, 1.5F, 4.149994F);
		static Vector3 o34 = new Vector3 (-9.359985F, 1.5F, 4.149994F);
		static Vector3 o35 = new Vector3 (-11.62F, 1.5F, 4.149994F);
		static Vector3 o36 = new Vector3 (14.64999F, 1.5F, 16.50999F);
		static Vector3 o37 = new Vector3 (9.98999F, 1.5F, 16.50999F);
		static Vector3 o38 = new Vector3 (5.820007F, 1.5F, 16.85001F);
		static Vector3 o39 = new Vector3 (2.380005F, 1.5F, 16.79001F);
		static Vector3 o40 = new Vector3 (2.299988F, 1.5F, 11.09F);
		static Vector3 o41 = new Vector3 (6F, 1.5F, 4.910004F);
		static Vector3 o42 = new Vector3 (2.720001F, 1.5F, 1.220001F);
		static Vector3 o43 = new Vector3 (-0.4500122F, 1.5F, -3.850006F);
		static Vector3 o44 = new Vector3 (2.690002F, 1.5F, -3.850006F);
		static Vector3 o45 = new Vector3 (5.730011F, 1.5F, -3.850006F);
		static Vector3 o46 = new Vector3 (8.820007F, 1.5F, -3.850006F);
		static Vector3 o47 = new Vector3 (13.67999F, 1.5F, -3.850006F);
		static Vector3 o48 = new Vector3 (13.67001F, 1.5F, -0.2599945F);
		static Vector3 o49 = new Vector3 (13.67001F, 1.5F, 4.210007F);
		static Vector3 o50 = new Vector3 (13.67001F, 1.5F, 8.139999F);
		static Vector3 o51 = new Vector3 (13.67001F, 1.5F, 11.14F);
		static Vector3 o52 = new Vector3 (-16.79001F, 1.5F, -9.740005F);
		static Vector3 o53 = new Vector3 (-9.880005F, 1.5F, -3.25F);
		static Vector3 o54 = new Vector3 (-6.859985F, 1.5F, -3.25F);
		static Vector3 o55 = new Vector3 (-8.019989F, 1.5F, -6.320007F);
		static Vector3 o56 = new Vector3 (-8.019989F, 1.5F, -9.759995F);
		static Vector3 o57 = new Vector3 (-8.019989F, 1.5F, -13.11F);
		static Vector3 o58 = new Vector3 (-0.6099854F, 1.5F, -10.82001F);
		static Vector3 o59 = new Vector3 (2.320007F, 1.5F, -12.14F);
		static Vector3 o60 = new Vector3 (5.559998F, 1.5F, -10.84F);
		static Vector3 o61 = new Vector3 (5.559998F, 1.5F, -13.46001F);
		static Vector3 o62 = new Vector3 (5.559998F, 1.5F, -16.04001F);
		static Vector3 o63 = new Vector3 (2.420013F, 1.5F, -14.83F);
		static Vector3 o64 = new Vector3 (-0.5299988F, 1.5F, -13.69F);
		static Vector3 o65 = new Vector3 (-4.549988F, 1.5F, -18.75F);
		static Vector3 o66 = new Vector3 (-2.779999F, 1.5F, -19.38F);
		static Vector3 o67 = new Vector3 (11.20999F, 1.5F, -17.97F);
		static Vector3 o68 = new Vector3 (11.20999F, 1.5F, -14.97F);
		static Vector3 o69 = new Vector3 (11.20999F, 1.5F, -11.42F);
		static Vector3 o70 = new Vector3 (23.57999F, 1.5F, -5.809998F);
		static Vector3 o71 = new Vector3 (0.480011F, 1.5F, -20.17F);
		
		static Vector3 f1 = new Vector3 (18.64001F, 1.5F, -7.800003F);
		static Vector3 f2 = new Vector3 (18.64001F, 1.5F, -3.029999F);
		static Vector3 f3 = new Vector3 (18.64001F, 1.5F, -1.179993F);
		static Vector3 f4 = new Vector3 (18.64001F, 1.5F, 1.080002F);
		static Vector3 f5 = new Vector3 (18.64001F, 1.5F, 3.479996F);
		static Vector3 f6 = new Vector3 (18.64001F, 1.5F, 5.789993F);
		static Vector3 f7 = new Vector3 (18.64001F, 1.5F, 7.940002F);
		static Vector3 f8 = new Vector3 (18.64001F, 1.5F, 10.25999F);
		static Vector3 f9 = new Vector3 (18.64001F, 1.5F, 12.61F);
		static Vector3 f10 = new Vector3 (18.64001F, 1.5F, 14.78999F);
		static Vector3 f11 = new Vector3 (18.64001F, 1.5F, 16.89999F);
		static Vector3 f12 = new Vector3 (18.64001F, 1.5F, 19.23F);
		static Vector3 f13 = new Vector3 (18.64001F, 1.5F, 21.41F);
		static Vector3 f14 = new Vector3 (18.64001F, 1.5F, 24.63F);
		static Vector3 f15 = new Vector3 (18.64001F, 1.5F, 24.63F);
		static Vector3 f16 = new Vector3 (18.64001F, 1.5F, 24.63F);
		static Vector3 f17 = new Vector3 (15.44F, 1.5F, 22.8F);
		static Vector3 f18 = new Vector3 (10.56F, 1.5F, 22.8F);
		static Vector3 f19 = new Vector3 (5.5F, 1.5F, 22.8F);
		static Vector3 f20 = new Vector3 (1.619995F, 1.5F, 22.8F);
		static Vector3 f21 = new Vector3 (-0.8999939F, 1.5F, 22.8F);
		static Vector3 f22 = new Vector3 (-2.399994F, 1.5F, 22.8F);
		static Vector3 f23 = new Vector3 (-3.640015F, 1.5F, 23.32001F);
		static Vector3 f24 = new Vector3 (-3.640015F, 1.5F, 24.17F);
		static Vector3 f25 = new Vector3 (-3.149994F, 1.5F, 23.22F);
		static Vector3 f26 = new Vector3 (-3.149994F, 1.5F, 19.89999F);
		static Vector3 f27 = new Vector3 (-11.82001F, 1.5F, 12.46001F);
		static Vector3 f28 = new Vector3 (-15.88F, 1.5F, 0.92F);
		static Vector3 f29 = new Vector3 (-11.76999F, 1.5F, 12.17999F);
		static Vector3 f30 = new Vector3 (-9.410004F, 1.5F, 12.17999F);
		static Vector3 f31 = new Vector3 (-3.589996F, 1.5F, 9.759995F);
		static Vector3 f32 = new Vector3 (-3.589996F, 1.5F, 6.979996F);
		static Vector3 f33 = new Vector3 (-3.589996F, 1.5F, 4.160004F);
		static Vector3 f34 = new Vector3 (-9.359985F, 1.5F, 0.9499969F);
		static Vector3 f35 = new Vector3 (-11.75F, 1.5F, 0.9499969F);
		static Vector3 f36 = new Vector3 (14.95999F, 1.5F, 20.8F);
		static Vector3 f37 = new Vector3 (9.809998F, 1.5F, 20.8F);
		static Vector3 f38 = new Vector3 (5.51001F, 1.5F, 20.8F);
		static Vector3 f39 = new Vector3 (-2.410004F, 1.5F, 18.22F);
		static Vector3 f40 = new Vector3 (-2.859985F, 1.5F, 12.23F);
		static Vector3 f41 = new Vector3 (-3.559998F, 1.5F, 6.539993F);
		static Vector3 f42 = new Vector3 (-3.559998F, 1.5F, 2.710007F);
		static Vector3 f43 = new Vector3 (-3.559998F, 1.5F, -2.449997F);
		static Vector3 f44 = new Vector3 (2.630005F, 1.5F, -6.139999F);
		static Vector3 f45 = new Vector3 (5.700012F, 1.5F, -6.139999F);
		static Vector3 f46 = new Vector3 (8.890015F, 1.5F, -6.139999F);
		static Vector3 f47 = new Vector3 (13.66F, 1.5F, -6.139999F);
		static Vector3 f48 = new Vector3 (18.56F, 1.5F, 1.050003F);
		static Vector3 f49 = new Vector3 (18.56F, 1.5F, 5.479996F);
		static Vector3 f50 = new Vector3 (18.56F, 1.5F, 9.440002F);
		static Vector3 f51 = new Vector3 (18.56F, 1.5F, 12.38F);
		static Vector3 f52 = new Vector3 (-15.25F, 1.5F, 0.9400024F);
		static Vector3 f53 = new Vector3 (-9.890015F, 1.5F, 0.9400024F);
		static Vector3 f54 = new Vector3 (-3.619995F, 1.5F, -1.759995F);
		static Vector3 f55 = new Vector3 (-3.619995F, 1.5F, -4.830002F);
		static Vector3 f56 = new Vector3 (-3.619995F, 1.5F, -8.5F);
		static Vector3 f57 = new Vector3 (-3.619995F, 1.5F, -11.69F);
		static Vector3 f58 = new Vector3 (-3.619995F, 1.5F, -8.979996F);
		static Vector3 f59 = new Vector3 (2.320007F, 1.5F, -6.050003F);
		static Vector3 f60 = new Vector3 (5.779999F, 1.5F, -6.050003F);
		static Vector3 f61 = new Vector3 (8.380005F, 1.5F, -12.08F);
		static Vector3 f62 = new Vector3 (5.570007F, 1.5F, -17.81F);
		static Vector3 f63 = new Vector3 (2.350006F, 1.5F, -17.61F);
		static Vector3 f64 = new Vector3 (-3.559998F, 1.5F, -13.81F);
		static Vector3 f65 = new Vector3 (-3.839996F, 1.5F, -17.29001F);
		static Vector3 f66 = new Vector3 (-1.980011F, 1.5F, -17.56F);
		static Vector3 f67 = new Vector3 (8.279999F, 1.5F, -18.22F);
		static Vector3 f68 = new Vector3 (8.279999F, 1.5F, -15.09F);
		static Vector3 f69 = new Vector3 (8.279999F, 1.5F, -11.49001F);
		static Vector3 f70 = new Vector3 (19.54001F, 1.5F, -6.419998F);
		static Vector3 f71 = new Vector3 (0.9700012F, 1.5F, -17.89999F);
		
		static Vector3 p1 = new Vector3 (18.44F, 1.5F, 22.79001F);
		static Vector3 p2 = new Vector3 (-3.660004F, 1.5F, 22.79001F);
		static Vector3 p3 = new Vector3 (-3.660004F, 1.5F, 12.17F);
		static Vector3 p4 = new Vector3 (-3.660004F, 1.5F, 0.8300018F);
		static Vector3 p5 = new Vector3 (-3.660004F, 1.5F, -6.179993F);
		static Vector3 p6 = new Vector3 (-3.660004F, 1.5F, -16.88F);
		static Vector3 p7 = new Vector3 (8.470001F, 1.5F, -6.259995F);
		static Vector3 p8 = new Vector3 (8.470001F, 1.5F, -20.13F);
		static Vector3 p9 = new Vector3 (18.60001F, 1.5F, -6.190002F);
		static Vector3 p10 = new Vector3 (-3.56f, 1.5f, 9.050003f);
		static Vector3 p11 = new Vector3 (-3.56f, 1.5f, 16.88f);
		
		
		static Vector3[] office1 = new Vector3[] { evelator, p11, p5, p9, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evelator, p11, p2, p1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evelator, p11, p2, p1, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evelator, p11, p2, p1, f4, o4 };
		static Vector3[] office5 = new Vector3[] { evelator, p11, p2, p1, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evelator, p11, p2, p1, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evelator, p11, p2, p1, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evelator, p11, p2, p1, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evelator, p11, p2, p1, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evelator, p11, p2, p1, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evelator, p11, p2, p1, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evelator, p11, p2, p1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evelator, p11, p2, p1, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evelator, p11, p2, p1, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evelator, p11, p2, p1, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evelator, p11, p2, p1, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evelator, p11, p2, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evelator, p11, p2, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evelator, p11, p2, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evelator, p11, p2, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evelator, p11, p2, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evelator, p11, p2, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evelator, p11, p2, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evelator, p11, p2, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evelator, p11, p2, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evelator, p11, f26, o26 };
		static Vector3[] office27 = new Vector3[] { evelator, p11, p3, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evelator, p11, p4, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evelator, p11, p3, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evelator, p11, p3, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evelator, p11, f31, o31 };
		static Vector3[] office32 = new Vector3[] { evelator, p11, f32, o32 };
		
		static Vector3[] office33 = new Vector3[] { evelator, p11, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evelator, p11, p4, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evelator, p11, p4, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evelator, p11, p2, f36, o36 };
		
		static Vector3[] office37 = new Vector3[] { evelator, p11, p2, f37, o37 };
		static Vector3[] office38 = new Vector3[] { evelator, p11, p2, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evelator, o39 };
		static Vector3[] office40 = new Vector3[] { evelator, p11, f40, o40 };
		
		static Vector3[] office41 = new Vector3[] { evelator, p11, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evelator, p11, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evelator, p11, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evelator, p11, p5, f44, o44 };
		static Vector3[] office45 = new Vector3[] { evelator, p11, p5, f45, o45 };
		static Vector3[] office46 = new Vector3[] { evelator, p11, p5, f46, o46 };
		static Vector3[] office47 = new Vector3[] { evelator, p11, p5, f47, o47 };
		static Vector3[] office48 = new Vector3[] { evelator, p11, p2, p1, f48, o48 };
		
		static Vector3[] office49 = new Vector3[] { evelator, p11, p2, p1, f49, o49 };
		static Vector3[] office50 = new Vector3[] { evelator, p11, p2, p1, f50, o50 };
		static Vector3[] office51 = new Vector3[] { evelator, p11, p2, p1, f51, o51 };
		static Vector3[] office52 = new Vector3[] { evelator, p11, p4, f52, o52 };
		static Vector3[] office53 = new Vector3[] { evelator, p11, p4, f53, o53 };
		static Vector3[] office54 = new Vector3[] { evelator, p11, f54, o54 };		
		static Vector3[] office55 = new Vector3[] { evelator, p11, f55, o55 };		
		
		static Vector3[] office56 = new Vector3[] { evelator, p11, f56, o56 };	
		static Vector3[] office57 = new Vector3[] { evelator, p11, f57, o57 };	
		static Vector3[] office58 = new Vector3[] { evelator, p11, f58, o58 };
		static Vector3[] office59 = new Vector3[] { evelator, p11, p5, f59, o59 };
		
		static Vector3[] office60 = new Vector3[] { evelator, p11, p5, f60, o60 };
		static Vector3[] office61 = new Vector3[] { evelator, p11, p5, f61, o61 };
		static Vector3[] office62 = new Vector3[] { evelator, p11, p6, f62, o62 };
		static Vector3[] office63 = new Vector3[] { evelator, p11, p6, f63, o63 };
		static Vector3[] office64 = new Vector3[] { evelator, p11, f64, o64 };
		
		static Vector3[] office65 = new Vector3[] { evelator, p11, f65, o65 };
		static Vector3[] office66 = new Vector3[] { evelator, p11, p6, f66, o66 };
		static Vector3[] office67 = new Vector3[] { evelator, p11, p5, p7, f67, o67 };
		static Vector3[] office68 = new Vector3[] { evelator, p11, p5, p7, f68, o68 };
		
		static Vector3[] office69 = new Vector3[] { evelator, p11, p5, p7, f69, o69 };
		static Vector3[] office70 = new Vector3[] { evelator, p11, p5, f70, o70 };
		static Vector3[] office71 = new Vector3[] { evelator, p11, p6, f71, o71 };
		
		static Vector3[] start1 = new Vector3[] { evelator, p11, p2, p1};
		static Vector3[] start2 = new Vector3[] { evelator, p11, p2};
		static Vector3[] start3 = new Vector3[] { evelator, p11, p3};
		static Vector3[] start4 = new Vector3[] { evelator, p11, p4};
		static Vector3[] start5 = new Vector3[] { evelator, p11, p5};
		static Vector3[] start6 = new Vector3[] { evelator, p11, p6};
		static Vector3[] start7 = new Vector3[] { evelator, p11, p5, p7};
		static Vector3[] start8 = new Vector3[] { evelator, p11, p6, p8};
		static Vector3[] start9 = new Vector3[] { evelator, p11, p5, p9};
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string, Vector3[]> dicStart = new Dictionary<string, Vector3[]>();
		
		public Point8_3handicap ()
		{						
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
			dictionary.Add("office45",office45);
			dictionary.Add("office46",office46);
			dictionary.Add("office47",office47);
			dictionary.Add("office48",office48);
			dictionary.Add("office49",office49);
			dictionary.Add("office50",office50);
			dictionary.Add("office51",office51);
			dictionary.Add("office52",office52);
			dictionary.Add("office53",office53);
			dictionary.Add("office54",office54);
			dictionary.Add("office55",office55);
			dictionary.Add("office56",office56);
			dictionary.Add("office57",office57);
			dictionary.Add("office58",office58);
			dictionary.Add("office59",office59);
			dictionary.Add("office60",office60);
			dictionary.Add("office61",office61);
			dictionary.Add("office62",office62);
			dictionary.Add("office63",office63);
			dictionary.Add("office64",office64);
			dictionary.Add("office65",office65);
			dictionary.Add("office66",office66);
			dictionary.Add("office67",office67);
			dictionary.Add("office68",office68);
			dictionary.Add("office69",office69);
			dictionary.Add("office70",office70);
			dictionary.Add("office71",office71);
			dicStart.Add ("start1", start1);
			dicStart.Add ("start2", start2);
			dicStart.Add ("start3", start3);
			dicStart.Add ("start4", start4);
			dicStart.Add ("start5", start5);
			dicStart.Add ("start6", start6);
			dicStart.Add ("start7", start7);
			dicStart.Add ("start8", start8);
			dicStart.Add ("start9", start9);
		}
		
		public void addNewOffice(string name, string nameStart, Vector3[] append,string camera)
		{
			Vector3[] start = dicStart [nameStart];
			int length = start.Length + append.Length;
			Vector3[] arrayVectorOffice = new Vector3[length];
			for (int i = 0; i< length; i++) {
				if(i<start.Length){
					arrayVectorOffice[i] = start[i];
				}
				else {
					arrayVectorOffice[i] = append[i - start.Length];
				}
			}
			dictionary.Add (name, arrayVectorOffice);
		}

	}
}

